# Generated by Django 3.2 on 2022-07-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeaboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='abouthome_image')),
                ('description', models.TextField()),
            ],
        ),
    ]
