# Generated by Django 3.2 on 2022-07-21 06:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0002_homeaboutus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeaboutus',
            options={'verbose_name': 'Home Aboutus', 'verbose_name_plural': 'Home Aboutus'},
        ),
        migrations.AlterField(
            model_name='homeaboutus',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
