# Generated by Django 3.2 on 2022-07-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0010_founder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='founder',
            old_name='images',
            new_name='image',
        ),
    ]
