# Generated by Django 3.2 on 2022-07-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0011_rename_images_founder_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeaboutus',
            name='subtitle',
        ),
        migrations.AlterField(
            model_name='homeaboutus',
            name='description',
            field=models.TextField(),
        ),
    ]
