# Generated by Django 3.2 on 2022-07-22 12:13

import autoslug.fields
import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0012_auto_20220722_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_criteria', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Donate Criteria',
                'verbose_name_plural': 'Donate Criteria',
            },
        ),
        migrations.CreateModel(
            name='Donatesection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_image', models.ImageField(upload_to='donatesection_image')),
                ('title', models.CharField(max_length=500)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('goal_show', models.BooleanField(default=False)),
                ('raised', models.IntegerField(blank=True, null=True)),
                ('goal', models.IntegerField(blank=True, null=True)),
                ('summary', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity_app.criteria')),
            ],
            options={
                'verbose_name': 'Donate Section',
                'verbose_name_plural': 'Donate Section',
            },
        ),
    ]
