# Generated by Django 3.2 on 2022-07-23 11:23

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0017_donate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainfounder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='founder')),
                ('title', models.CharField(max_length=500)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Main Founder',
                'verbose_name_plural': 'Main Founder',
            },
        ),
    ]
