# Generated by Django 3.2 on 2022-07-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0018_mainfounder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainfounder',
            old_name='title',
            new_name='name',
        ),
    ]
