# Generated by Django 3.2 on 2022-07-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0019_rename_title_mainfounder_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('tropic', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery',
            },
        ),
    ]
