# Generated by Django 3.2 on 2022-07-25 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0020_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
