# Generated by Django 3.2 on 2022-07-25 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0022_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='title',
            new_name='sub_title',
        ),
    ]
