# Generated by Django 3.2 on 2022-07-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0023_rename_title_gallery_sub_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Faq',
                'verbose_name_plural': 'Faq',
            },
        ),
    ]
