# Generated by Django 3.2 on 2022-07-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0027_remove_blog_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
