# Generated by Django 3.2 on 2022-07-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0033_becomeavolunteer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Becomeavolunteer',
        ),
    ]
