# Generated by Django 3.2 on 2022-07-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0034_delete_becomeavolunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Becomeavolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volunteerid', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='volunteer')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('area', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=13)),
                ('equalification', models.CharField(max_length=200)),
                ('preaddress', models.CharField(max_length=200)),
                ('paraddress', models.CharField(max_length=200)),
                ('fathername', models.CharField(max_length=200)),
                ('mothername', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=10)),
                ('institute', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=80)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Become a Volunteer',
                'verbose_name_plural': 'Become a Volunteer',
            },
        ),
    ]
