# Generated by Django 3.2 on 2022-07-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0036_alter_becomeavolunteer_volunteerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventregistation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.IntegerField()),
                ('eventname', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('registationtype', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Event Registation',
                'verbose_name_plural': 'Event Registation',
            },
        ),
    ]
