# Generated by Django 3.2 on 2022-07-26 10:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0039_alter_eventregistation_eventid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sendgift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Send a Gift',
                'verbose_name_plural': 'Send a Gift',
            },
        ),
    ]
