# Generated by Django 3.2 on 2022-07-27 05:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0041_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'About More',
                'verbose_name_plural': 'About More',
            },
        ),
    ]
