# Generated by Django 3.2 on 2022-07-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity_app', '0046_noticesection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoticeSection',
            new_name='Notice',
        ),
    ]
